Nouveau simulateur cotisation Cipav 2023
betagouv/mon-entreprise pull request #2304
Opened 2022-10-03 13:45 UTC by mquandalle

Le montant des cotisations retraite change en 2023 pour les indépendants affiliés à la Cipav à l'occasion du transfert de la collecte des cotisations à l'Urssaf, cf. https://www.urssaf.fr/portail/home/independant/cipav/transfert-des-cotisations-cipav.html

Qu'est-ce que ça change pour moi ? Mes cotisations vont-elles augmenter ? Ces sans doute les premières questions que les personnes concernées vont se poser, et auquel un petit simulateur peut bien mieux répondre qu'un texte descriptif de la nouvelle formule de calcul comme dans l'actu Urssaf actuelle.

Ce simulateur pourra être intégré sur les sites de l'Urssaf et de la Cipav.

2022-10-05 11:24 UTC, johangirod reviewed
Petit problème : l'affichage sur mobile est cassé.

Par ailleurs, j'ai l'impression que le montant des cotisations augmente dans la plupart des cas. Est-ce que ça ne vaudrait pas le coup d'ajouter en face les notions de droits ouverts ? Voir les calculer ?

Je pense qu'un simulateur avec ces résultats + la marque Urssaf, c'est assuré d'avoir un nombre élevé de personnes qui cliquent sur l'emoji « pas content », ce qui va encore plomber nos stats.

C'est pas forcément grave puisque in fine, on rend service aux usagers, mais il faut le savoir.

2022-10-05 11:24 UTC, johangirod commented on site/source/pages/Simulateurs/Cipav2023.tsx
> +				className="ui__ light card"
Ces classes css sont dépréciées et ne marchent plus dans la version actuel il me semble

2022-10-05 11:24 UTC, johangirod commented on modele-social/règles/profession-libérale.yaml
> +dirigeant . indépendant . PL . CIPAV . cotisation 2023:
Depuis l'ouverture de l'API, il faut veiller à ne pas introduire des noms de règles qui pourraient être supprimés plus tard.
Deux possibilités : 

1. Réécrire les règles sous forme de variations sur les dates. À savoir : il s'agit des cotisations de 2022 qui seront impactées, il faut donc veiller à prendre 01/01/2022 comme pivot. On peut alterner entre les deux versions grâce au mécanisme `recalcul`
2. Ajouter un tag `experimental` si on veut aller vite quick & dirty :)

2022-10-05 11:25 UTC, johangirod commented on modele-social/règles/profession-libérale.yaml
> +dirigeant . indépendant . PL . CIPAV . cotisation 2023:
En fait je n'arrive pas à comprendre si il s'agit des cotisations de 2022 (qui seront payées via le rattrapage en 2023), ou celle de 2023 (et le changement aura lieu que pour le calcul des cotisations provisionnelles 2023).

2022-10-05 12:58 UTC, mquandalle commented
> Je pense qu'un simulateur avec ces résultats + la marque Urssaf, c'est assuré d'avoir un nombre élevé de personnes qui cliquent sur l'emoji « pas content », ce qui va encore plomber nos stats. C'est pas forcément grave puisque in fine, on rend service aux usagers, mais il faut le savoir.

Oui, pour l'instant sans cet outil l'Urssaf envoie un mail à 500k personnes pour leur dire « le calcul de votre cotisation retraite _va changer_ l’année prochaine », et vu que le sujet retraite est tendu et que l'Urssaf et la Cipav ne sont pas vraiment nos _amis_, j'imagine que la satisfaction ne va pas être exceptionnelle. Maintenant partant de là, il me semble clair aussi que le mini-simulateur avant / après améliore la situation en répondant aux questions précises qui se posent, indépendamment du clic sur les emojies. 

> EDIT : dernier, point, ça peut être pas mal d'ajouter un bandeau beta, vu les tensions qui existent entre mon-entreprise & Urssaf au moment de la mise en ligne, ça coûte rien, et ça peut éviter d'ajouter de l'huile sur le feu pour la suite.

Pas tellement d'accord, c'est du “one-shot” qui n'a pas vocation à perdurer au delà de 2023, si c'est en beta maintenant ça le restera tout le temps (alors que j'avais en tête que l'idée était de retirer les bandeaux beta à terme). Par ailleurs on intègre déjà le barème Cipav 2022 sans bandeau béta et il faudra ajouter le 2023 dans tous les cas donc au niveau des règles je ne vois pas de justification de les afficher comme beta (outre que le calcul n'est pas bien compliqué).

Je te laisse arbitrer là-dessus, mais je vois pas du tout cet outil comme pouvant générer des tensions avec l'Urssaf.

2022-10-05 12:59 UTC, mquandalle commented on modele-social/règles/profession-libérale.yaml
> +dirigeant . indépendant . PL . CIPAV . cotisation 2023:
c'est la cotis 2023

2022-11-15 21:49 UTC, quentinbt requested changes

2022-11-15 21:49 UTC, quentinbt commented on site/source/pages/Simulateurs/Cipav2023.tsx
> +		<>
fragment inutile

2022-12-31 09:53 UTC, closed without merging