Mise en conformité RGAA : Formulaires
betagouv/mon-entreprise pull request #2374
Opened 2022-11-03 14:11 UTC by bjlaa

https://www.notion.so/mon-entreprise/11-Formulaires-2c404596aa55491886689443c6d09724

2022-11-15 21:36 UTC, quentinbt requested changes

2022-11-15 21:36 UTC, quentinbt commented on site/source/components/Simulation/index.tsx
> +						la modification d'un champ.
texte non traduit

2022-11-15 21:36 UTC, quentinbt commented on site/source/components/conversation/AnswerList.tsx
> +							Cette opération n'est pas réversible.
texte non traduit

2022-11-15 21:36 UTC, quentinbt commented on site/source/components/conversation/InputSuggestions.tsx
> +						aria-label={`${t('Insérer dans le champ la valeur du')} ${text}`}
Dans le cas d'une variable dans un string à traduire on est censé la passé à l'outil et ce pour plusieurs raison:
1- on donne du contexte au traducteur
2- dans certaine langue cette variable peut se retrouver ailleurs dans la phrase

2022-11-15 21:36 UTC, quentinbt commented on site/source/pages/Landing/SearchOrCreate.tsx
> +											Réinitialiser
texte non traduit

2022-11-15 21:36 UTC, quentinbt commented on site/source/pages/Landing/SearchOrCreate.tsx
> +									title="Êtes-vous sûr de vouloir réinitialiser la situation enregistrée ?"
text non traduit

2022-11-15 21:36 UTC, quentinbt commented on site/source/pages/Simulateurs/metadata.tsx
> +							aria-label="Effectuer la demande de chômage partiel, accéder à la page dédiée, nouvelle fenêtre"
texte non traduit

2022-11-15 21:36 UTC, quentinbt commented on site/source/pages/Simulateurs/metadata.tsx
> +							aria-label="le site de l'Urssaf, accéder au site de l'Urssaf, nouvelle fenêtre"
text non traduit

2022-11-15 21:36 UTC, quentinbt commented on site/source/pages/Simulateurs/metadata.tsx
> +						<Link
sauf erreur de ma part Link est utile seulement dans les liens interne à next pour permettre la gestion automatique csr, ssr etc.. ici on a un lien externe donc un tag devrait suffir

2022-11-15 21:36 UTC, quentinbt commented on site/source/design-system/popover/PopoverConfirm.tsx
> +	const state = useOverlayTriggerState({})
state me semble trop générique comme nom de variable

2022-11-15 21:36 UTC, quentinbt commented on site/source/design-system/popover/PopoverConfirm.tsx
> +	confirmLabel = 'Confirmer',
text non traduit

2022-11-15 21:36 UTC, quentinbt commented on site/source/components/Feedback/FeedbackForm.tsx
> +							void sendMessage({ message: messageValue, email: emailValue })
si on nomme les variables convenablement on peut simplifier par `void sendMessage({ message, email })`

2022-11-16 15:11 UTC, bjlaa commented on site/source/components/Simulation/index.tsx
> +						la modification d'un champ.
Salut Quentin ! Merci pour tes retours j'ai normalement pu tout traiter :)

2022-11-16 15:11 UTC, bjlaa commented on site/source/components/conversation/AnswerList.tsx
> +							Cette opération n'est pas réversible.
C'est corrigé, merci !

2022-11-16 15:11 UTC, bjlaa commented on site/source/components/conversation/InputSuggestions.tsx
> +						aria-label={`${t('Insérer dans le champ la valeur du')} ${text}`}
Bien vu, c'est corrigé !

2022-11-16 15:11 UTC, bjlaa commented on site/source/pages/Landing/SearchOrCreate.tsx
> +											Réinitialiser
C'est corrigé, merci !

2022-11-16 15:11 UTC, bjlaa commented on site/source/pages/Simulateurs/metadata.tsx
> +							aria-label="Effectuer la demande de chômage partiel, accéder à la page dédiée, nouvelle fenêtre"
C'est corrigé, merci !

2022-11-16 15:12 UTC, bjlaa commented on site/source/pages/Simulateurs/metadata.tsx
> +							aria-label="le site de l'Urssaf, accéder au site de l'Urssaf, nouvelle fenêtre"
C'est corrigé, merci !

2022-11-16 15:14 UTC, bjlaa commented on site/source/pages/Simulateurs/metadata.tsx
> +						<Link
Ici `Link` est le composant de notre design-system donc à priori pas de problème :)

2022-11-16 15:23 UTC, bjlaa commented on site/source/design-system/popover/PopoverConfirm.tsx
> +	confirmLabel = 'Confirmer',
Corrigé :)

2022-11-16 15:23 UTC, bjlaa commented on site/source/components/Feedback/FeedbackForm.tsx
> +							void sendMessage({ message: messageValue, email: emailValue })
Corrigé, merci !

2022-11-21 13:59 UTC, quentinbt approved these changes

2022-11-23 17:02 UTC, merged