Feature_#1909_BNC_Affichage
betagouv/mon-entreprise pull request #2869
Opened 2024-01-13 21:43 UTC by Souleymane9

Bonjour,

Voici une proposition de résolution de l'issue #1909 relative à la mise en place d'un affichage sur le BNC et la distinction entre les notions BNC et micro BNC.
Ci-joint un screen du résultat : 
<img width="1440" alt="Capture d’écran 2024-01-13 à 22 32 38" src="https://github.com/betagouv/mon-entreprise/assets/64657952/9847ab44-65d7-46d7-833f-c59ae74829a6">

Voici la page concernée : https://mon-entreprise.urssaf.fr/simulateurs/artiste-auteur .

Je vous remercie d'avance.

2024-02-22 21:23 UTC, JalilArfaoui requested changes
Merci pour cette proposition @Souleymane9 ! 

Cependant, il y a plusieurs petits changements que je ne comprends pas et qui semblent sans rapport avec l'objet de cette PR....

Pourriez-vous vérifier ?

2024-02-22 21:23 UTC, JalilArfaoui commented on .vscode/settings.json
> +		"source.fixAll.eslint": "explicit"
Pourquoi changer la configuration VS Code ?

2024-02-22 21:23 UTC, JalilArfaoui commented on modele-social/règles/salarié/activité-partielle.yaml
> +    L'ajouter abouti à un calcul cyclique (vu quelle dépend du montant de la CSG)
C'est bien "qu'elle" qui est la bonne orthographe

2024-02-22 21:23 UTC, JalilArfaoui commented on modele-social/règles/salarié/activité-partielle.yaml
> +      activité partielle: oui
Pourquoi ce changement de règle ?

2024-02-22 21:23 UTC, JalilArfaoui commented on site/source/pages/simulateurs/artiste-auteur/ArtisteAuteur.tsx
> +				<H2>
Pourquoi ce titre vide ?

2024-02-22 21:23 UTC, JalilArfaoui commented on site/source/pages/simulateurs/chômage-partiel/ChômagePartiel.tsx
> +						label={t('Salaire brut mensuelle')}
C'est bien "mensuel" au masculin qu'il faut garder.

2024-02-22 21:56 UTC, Souleymane9 commented on .vscode/settings.json
> +		"source.fixAll.eslint": "explicit"
J'ignore comment ces changements ont eu lieu, sûrement une mauvaise manipulation.
Je vais essayer de changer tout ce qui est inutile.

2024-02-22 21:56 UTC, Souleymane9 commented on modele-social/règles/salarié/activité-partielle.yaml
> +    L'ajouter abouti à un calcul cyclique (vu quelle dépend du montant de la CSG)
Pareil, tout à fait d''accord avec vous. Je corrige...

2024-02-22 21:57 UTC, Souleymane9 commented on modele-social/règles/salarié/activité-partielle.yaml
> +    L'ajouter abouti à un calcul cyclique (vu quelle dépend du montant de la CSG)
Encore pareil mauvaise manipulation sûrement. Je change cela.

2024-02-22 21:57 UTC, Souleymane9 commented on modele-social/règles/salarié/activité-partielle.yaml
> +    L'ajouter abouti à un calcul cyclique (vu quelle dépend du montant de la CSG)
Je change.

2024-02-22 21:58 UTC, Souleymane9 commented on modele-social/règles/salarié/activité-partielle.yaml
> +      activité partielle: oui
Encore pareil mauvaise manipulation sûrement. Je change cela.

2024-02-22 21:58 UTC, Souleymane9 commented on site/source/pages/simulateurs/artiste-auteur/ArtisteAuteur.tsx
> +				<H2>
Je change cela.

2024-02-22 21:59 UTC, Souleymane9 commented on site/source/pages/simulateurs/chômage-partiel/ChômagePartiel.tsx
> +						label={t('Salaire brut mensuelle')}
Je change.

2024-03-06 23:10 UTC, JalilArfaoui commented
@Souleymane9  c’est mieux, mais il y a toujours des changements sans rapport, notamment dans modele-social/règles/salarié/activité-partielle.yaml…

2024-03-07 23:50 UTC, Souleymane9 commented
> @Souleymane9 c’est mieux, mais il y a toujours des changements sans rapport, notamment dans modele-social/règles/salarié/activité-partielle.yaml…

2024-03-07 23:50 UTC, closed without merging

2024-03-07 23:54 UTC, Souleymane9 commented
Je vois que le fichier social/règles/salarié/activité-partielle.yaml… n'est plus au format .yaml mais en .publicodes, ce qui signifie que l'extension a été changée. Je vais peut-être fermer ce PR et repartir du Repo à jour avec les nouvelles extensions.