fix(artiste-auteur): màj seuils cotisation RAAP
betagouv/mon-entreprise pull request #3008
Opened 2024-07-08 11:14 UTC by logic-fabric

close #3001 

Cette PR :
- met à jour le seuil qui passe à 10 143 €
- met en place le plafond de 139 104 € pour l'assiette

2024-07-10 08:20 UTC, johangirod approved these changes

2024-07-10 08:20 UTC, johangirod commented on modele-social/règles/artiste-auteur.publicodes
> -artiste-auteur . cotisations . IRCEC . cotisation RAAP . seuil d'affiliation: 9135 €/an
On préfère généralement garder l'historique des valeurs dans notre base de règle. Cela permet : 
- de proposer des simulations sur des années antérieures ;
- de pouvoir facilement naviguer toutes les valeurs historicisées, et donc de faciliter leur mise à jour chaque année.

2024-07-10 08:33 UTC, johangirod requested changes

2024-07-10 08:33 UTC, johangirod commented on modele-social/règles/artiste-auteur.publicodes
> -            assiette: assiette
Deux petits commentaires : 

1. La valeur inscrite dans le guide de référence est 139104 €, seulement une note précise que cela correspond à 3 fois le montant du plafond de la sécurité sociale. **De manière générale, il faut se méfier des valeurs absolues inscrites dans le dur dans les textes explicatifs**. Très souvent, la source de vérité est un pourcentage d'une autre valeur. Il faut la chercher : 
   - Dans les guides
   - Dans la loi
   - Par rétro-ingénierie, en vérifiant si la valeur n'est pas un pourcentage rond d'une valeur célèbre : SMIC, PASS, RCI, ...

3. On préfère plafonner le barème directement que d'ajouter un plafond à l'assiette, cela est plus lisible. Ainsi, on peut écrire : 
    ```yaml
   tranches:
              - taux: 4%
                plafond:
                  variations:
                    - si: profession . RACD
                      alors: cotisation RACD . plafond
                    - si: profession . RACL
                      alors: cotisation RACL . plafond
              - taux: 8%
                plafond: 300% * plafond sécurité sociale
    ```

2024-07-11 08:20 UTC, logic-fabric commented on modele-social/règles/artiste-auteur.publicodes
> -artiste-auteur . cotisations . IRCEC . cotisation RAAP . seuil d'affiliation: 9135 €/an
Bonne idée de garder une trace oui. 🙂

Si je me réfère aux autres fichiers `.publicodes` pour être consistant, je vais mettre ceci :

```yaml
# Avant 2024, le seuil d'affiliation était de 9135 €/an
artiste-auteur . cotisations . IRCEC . cotisation RAAP . seuil d'affiliation: 10143 €/an
```

2024-07-11 08:25 UTC, logic-fabric commented on modele-social/règles/artiste-auteur.publicodes
> -            assiette: assiette
Bien vu pour la note. On a regardé un peu vite la doc, tout content d'avoir déjà vu que ce plafond était absent. ^^

Je vais juste mettre `plafond: 3 * plafond sécurité sociale` au lieu d'utiliser un `300%`. C'est plus simple et plus raccord avec la formulation de la doc.

2024-07-11 08:33 UTC, logic-fabric commented on modele-social/règles/artiste-auteur.publicodes
> -artiste-auteur . cotisations . IRCEC . cotisation RAAP . seuil d'affiliation: 9135 €/an
Commit amendé. 🙂

2024-07-12 11:39 UTC, johangirod approved these changes

2024-07-12 11:39 UTC, johangirod commented on modele-social/règles/artiste-auteur.publicodes
> +              valeur: assiette
Cela peut être simplifié en 
```yaml
assiette: assiette
```

2024-07-12 11:39 UTC, johangirod commented on modele-social/règles/artiste-auteur.publicodes
> -artiste-auteur . cotisations . IRCEC . cotisation RAAP . seuil d'affiliation: 9135 €/an
Je pensais plus à l'utilisation de la variable `date` pour historiser. 

Cf le cas d'usage ici : https://github.com/betagouv/mon-entreprise/blob/master/modele-social/r%C3%A8gles/dirigeant/ind%C3%A9pendant.publicodes#L585-L594

2024-07-12 12:57 UTC, logic-fabric commented on modele-social/règles/artiste-auteur.publicodes
> -artiste-auteur . cotisations . IRCEC . cotisation RAAP . seuil d'affiliation: 9135 €/an
Commit amendé dans ce sens. 🙂

2024-07-12 12:58 UTC, logic-fabric commented on modele-social/règles/artiste-auteur.publicodes
> +              valeur: assiette
Effectivement, sans `plafond`, deux lignes ne sont plus nécessaires.

Commit amendé. 🙂

2024-07-15 12:45 UTC, johangirod approved these changes
Top, c'est nickel, merci pour les changements :+1:

2024-07-16 17:24 UTC, JalilArfaoui commented on modele-social/règles/artiste-auteur.publicodes
> -artiste-auteur . cotisations . IRCEC . cotisation RAAP . seuil d'affiliation: 9135 €/an
On avait modifié car le taux affiché était de 2022, on a dans le code ni celui de 2023 ni celui de 2021… 😅 

Pour toi @johangirod l’idée est de systématiquement garder l’historique pour toutes les valeurs ? 

Dans le code existant, il y a parfois l’historique, parfois non…

2024-07-16 17:37 UTC, JalilArfaoui commented
@logic-fabric peux-tu rebase sur `master`, ça devrait permettre d’avoir une validation d’intégration continue OK

2024-07-16 17:48 UTC, JalilArfaoui commented
Au temps pour moi @logic-fabric, j’ai demandé un rebase via Github…

2024-07-16 17:59 UTC, merged