Feat(auto-entrepreneur): Ajoute les taux de cotisation BNC à venir pour 2025 et 2026
betagouv/mon-entreprise pull request #3045
Opened 2024-07-26 13:42 UTC by liliced

- Augmentations du taux en 2025 et 2026
- Changement de la répartition des cotisations
- Changement du taux Acre BNC en 2026

2024-07-31 15:49 UTC, JalilArfaoui requested changes
Peut-être en profiter pour mettre également les taux DROM des prochaines années ? 
(Page 7 de https://legislation.lassuranceretraite.fr/Pdf/circulaire_cnav_2024_23_16072024.pdf)

2024-07-31 15:49 UTC, JalilArfaoui commented on modele-social/règles/dirigeant/auto-entrepreneur/exonérations.publicodes
> +            arrondi:
Pourquoi changer les règles d'arrondi en fonction de la date ?

2024-07-31 15:49 UTC, JalilArfaoui commented on modele-social/règles/protection-sociale.publicodes
> +            - entreprise . chiffre d'affaires . service BNC
Tu peux annuler les modifs de ce fichier qui seront caduques dès que j'aurais mergé https://github.com/betagouv/mon-entreprise/pull/3026 😅

2024-08-01 08:00 UTC, liliced commented on modele-social/règles/dirigeant/auto-entrepreneur/exonérations.publicodes
> +            arrondi:
Parce qu'à partir de 2026 le taux est arrondi à 2 chiffres après la virgule alors qu'il l'était à 1 avant :
- Avant juillet 2024 : 50% * 21,1 = 10,55 => arrondi à 10,6 %
- 50% * 23,1 = 11,55 => arrondi à 11,6%
- À partir de 2026 : 50% * 26,10 = 13,05 => **pas** arrondi à 13,1%

![image](https://github.com/user-attachments/assets/18264f99-1fc9-48ce-9ddc-9f0c29bb487d)

2024-08-01 08:53 UTC, JalilArfaoui commented on modele-social/règles/dirigeant/auto-entrepreneur/exonérations.publicodes
> +            arrondi:
Ah oui, c’est fou ça… Merci !

2024-08-01 12:22 UTC, JalilArfaoui approved these changes

2024-08-01 13:01 UTC, merged