Fix(artiste-auteur): Rend applicable l'option de surcotisation forfaitaire pour les revenus artistiques à 0
betagouv/mon-entreprise pull request #3049
Opened 2024-07-26 14:43 UTC by liliced

2024-08-01 08:46 UTC, JalilArfaoui requested changes

2024-08-01 08:46 UTC, JalilArfaoui commented on site/test/regressions/artiste-auteur.test.ts
> +		  "artiste-auteur . cotisations . option surcotisation",
Pas de changement côté snapshot ?

2024-08-01 09:38 UTC, liliced commented on site/test/regressions/artiste-auteur.test.ts
> +		  "artiste-auteur . cotisations . option surcotisation",
A priori non :shrug:

2024-08-13 15:41 UTC, liliced commented on site/test/regressions/artiste-auteur.test.ts
> +		  "artiste-auteur . cotisations . option surcotisation",
Non. Le problème était que la question n'était pas proposée.
Mais j'ai rajouté des tests avec revenus à 0 et option surcotisation.

2024-08-16 15:04 UTC, JalilArfaoui approved these changes

2024-08-19 07:30 UTC, merged